Repository pulanski/codeswipe, pull requests merged in 2023-10, with the labels that each got.

#2 Setup
  src/app/page.tsx
Labels: Extra Small

#6 Create ui library
  components.json
  next.config.mjs
  package.json
  pnpm-lock.yaml
  src/app/_components/ui/button.tsx
  src/app/landing/page.tsx
  src/env.mjs
  src/lib/utils.ts
  src/styles/globals.css
  tailwind.config.ts
Labels: Extra Large

#10 feat(ui): add landing footer and nav components
  drizzle.config.ts
  package.json
  pnpm-lock.yaml
  public/favicon.ico
  public/logo.png
  src/app/_components/footer.tsx
  src/app/_components/logo.tsx
  src/app/_components/tinder-landing.tsx
  src/server/db/schema.ts
Labels: Extra Large

#11 Create sign-up page
  src/app/sign-up/page.tsx
Labels: Medium

#13 feat(landing): add landing page w/ components
  src/app/_components/Navbar.tsx
  src/app/_components/logo.tsx
  src/app/api/auth/[...nextauth]/route.ts
  src/app/api/trpc/[trpc]/route.ts
  src/app/landing/layout.tsx
  src/app/landing/page.tsx
  src/app/layout.tsx
Labels: Medium
